package com.zshgif.laugh.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.zshgif.laugh.dao.db.DBHelper;

/**
 * Entity mapped to table VIDEO_BEAN.
 */
public class VideoBean {

    private Long id;
    /**
     * �ں�����Id
     */
    private long NETid;
    /** Not-null value. */
    /**
     * ����
     */
    private String content;
    /** Not-null value. */
    /**
     * ��������
     */
    private String category_name;
    /** Not-null value. */
    /**
     * ��һ��ͼ��ַ
     */
    private String firstOne;
    /**
     * ��Ƶ��ַ
     */
    private String videoUrl;
    /**
     * ��Ƶ�г�
     */
    private int timeLenth;
    /**
     * ���
     */
    private int width;
    /**
     * �߶�
     */
    private int height;
    /**
     * ͼƬ���� 1 ����ͼƬ  3 ����GIF  5 ��ͼ
     */
    private int type;
    /**
     * ��
     */
    private int digg_count;
    /**
     * ����
     */
    private int bury_count;
    /**
     * ������
     */
    private int comments_count;
    /** Not-null value. */
    /**
     * �����ַ
     */
    private String share_url;

    /**
     * 评论者
     */
    private CommentsBean comments;

    /**
     * 发布者
     */
    private ReleaseUser releaseUser;

    public VideoBean() {
    }

    public VideoBean(Long id) {
        this.id = id;
    }

    public VideoBean(Long id, long NETid, String content, String category_name, String firstOne, String videoUrl, int timeLenth, int width, int height, int type, int digg_count, int bury_count, int comments_count, String share_url) {
        this.id = id;
        this.NETid = NETid;
        this.content = content;
        this.category_name = category_name;
        this.firstOne = firstOne;
        this.videoUrl = videoUrl;
        this.timeLenth = timeLenth;
        this.width = width;
        this.height = height;
        this.type = type;
        this.digg_count = digg_count;
        this.bury_count = bury_count;
        this.comments_count = comments_count;
        this.share_url = share_url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getNETid() {
        return NETid;
    }

    public void setNETid(long NETid) {
        this.NETid = NETid;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    /** Not-null value. */
    public String getCategory_name() {
        return category_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory_name(String category_name) {
        this.category_name = category_name;
    }

    /** Not-null value. */
    public String getFirstOne() {
        return firstOne;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirstOne(String firstOne) {
        this.firstOne = firstOne;
    }

    public String getVideoUrl() {
        return videoUrl;
    }

    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    public int getTimeLenth() {
        return timeLenth;
    }

    public void setTimeLenth(int timeLenth) {
        this.timeLenth = timeLenth;
    }

    public int getWidth() {
        return width;
    }

    public void setWidth(int width) {
        this.width = width;
    }

    public int getHeight() {
        return height;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public int getDigg_count() {
        return digg_count;
    }

    public void setDigg_count(int digg_count) {
        this.digg_count = digg_count;
    }

    public int getBury_count() {
        return bury_count;
    }

    public void setBury_count(int bury_count) {
        this.bury_count = bury_count;
    }

    public int getComments_count() {
        return comments_count;
    }

    public void setComments_count(int comments_count) {
        this.comments_count = comments_count;
    }

    /** Not-null value. */
    public String getShare_url() {
        return share_url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setShare_url(String share_url) {
        this.share_url = share_url;
    }
    public CommentsBean getComments() {
        if(comments==null){
            return DBHelper.loadCommentsBean(NETid);
        }
        return comments;
    }

    public void setComments(CommentsBean comments) {
        this.comments = comments;
        comments.setNETid(NETid);
        DBHelper.insertIntoCommentsBean(comments);
    }

    public ReleaseUser getReleaseUser() {
        if(releaseUser==null){
            return DBHelper.loadReleaseUser(NETid);
        }
        return releaseUser;
    }

    public void setReleaseUser(ReleaseUser releaseUser) {
        this.releaseUser = releaseUser;
        releaseUser.setNETid(NETid);
        DBHelper.insertIntoReleaseUser(releaseUser);
    }
}
