package com.zshgif.laugh.model;

import com.zshgif.laugh.dao.GifitemBeanDao;
import com.zshgif.laugh.dao.PictureBeanDao;
import com.zshgif.laugh.dao.db.DBHelper;
import com.zshgif.laugh.dao.db.DaoSession;

import java.util.List;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table GIFITEM_BEAN.
 */
public class VideoBean {

    private Long id;
    /**
     * 内涵段子Id
     */
    private long NETid;
    /** Not-null value. */
    /**
     * 内容
     */
    private String content;
    /** Not-null value. */
    /**
     * 分类名称
     */
    private String category_name;
    /** Not-null value. */
    /**
     * 第一张图地址
     */
    private String firstOne;
    /**
     * 视频地址
     */
    private String videoUrl;
    /**
     * 视频市场
     */
    private int timeLenth;
    /**
     * 宽度
     */
    private int width;
    /**
     * 高度
     */
    private int height;
    /**
     * 图片类型 1 单张图片  3 单张GIF  5 多图
     */
    private int type;
    /**
     * 赞
     */
    private int digg_count;
    /**
     * 鄙视
     */
    private int bury_count;
    /**
     * 评论数
     */
    private int comments_count;
    /** Not-null value. */
    /**
     * 分享地址
     */
    private String share_url;


    /**
     * 评论者
     */
    private CommentsBean comments;

    /**
     * 发布者
     */
    private ReleaseUser releaseUser;


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getNETid() {
        return NETid;
    }

    public void setNETid(long NETid) {
        this.NETid = NETid;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getCategory_name() {
        return category_name;
    }

    public void setCategory_name(String category_name) {
        this.category_name = category_name;
    }

    public String getFirstOne() {
        return firstOne;
    }

    public void setFirstOne(String firstOne) {
        this.firstOne = firstOne;
    }

    public String getVideoUrl() {
        return videoUrl;
    }

    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    public int getTimeLenth() {
        return timeLenth;
    }

    public void setTimeLenth(int timeLenth) {
        this.timeLenth = timeLenth;
    }

    public int getWidth() {
        return width;
    }

    public void setWidth(int width) {
        this.width = width;
    }

    public int getHeight() {
        return height;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public int getDigg_count() {
        return digg_count;
    }

    public void setDigg_count(int digg_count) {
        this.digg_count = digg_count;
    }

    public int getBury_count() {
        return bury_count;
    }

    public void setBury_count(int bury_count) {
        this.bury_count = bury_count;
    }

    public int getComments_count() {
        return comments_count;
    }

    public void setComments_count(int comments_count) {
        this.comments_count = comments_count;
    }

    public String getShare_url() {
        return share_url;
    }

    public void setShare_url(String share_url) {
        this.share_url = share_url;
    }

    public CommentsBean getComments() {
        return comments;
    }

    public void setComments(CommentsBean comments) {
        this.comments = comments;
    }

    public ReleaseUser getReleaseUser() {
        return releaseUser;
    }

    public void setReleaseUser(ReleaseUser releaseUser) {
        this.releaseUser = releaseUser;
    }
}
