package com.cn.speedchat.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COMMENTSBEAN.
 */
public class CommentsBean {

    private Long id;
    private long NETid;
    /** Not-null value. */
    private String commentUserName;
    /** Not-null value. */
    private String commentUserProfile;
    /** Not-null value. */
    private String comment;

    public CommentsBean() {
    }

    public CommentsBean(Long id) {
        this.id = id;
    }

    public CommentsBean(Long id, long NETid, String commentUserName, String commentUserProfile, String comment) {
        this.id = id;
        this.NETid = NETid;
        this.commentUserName = commentUserName;
        this.commentUserProfile = commentUserProfile;
        this.comment = comment;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getNETid() {
        return NETid;
    }

    public void setNETid(long NETid) {
        this.NETid = NETid;
    }

    /** Not-null value. */
    public String getCommentUserName() {
        return commentUserName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCommentUserName(String commentUserName) {
        this.commentUserName = commentUserName;
    }

    /** Not-null value. */
    public String getCommentUserProfile() {
        return commentUserProfile;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCommentUserProfile(String commentUserProfile) {
        this.commentUserProfile = commentUserProfile;
    }

    /** Not-null value. */
    public String getComment() {
        return comment;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setComment(String comment) {
        this.comment = comment;
    }

}
