package com.cn.speedchat.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cn.speedchat.greendao.GifitemBean;
import com.cn.speedchat.greendao.PictureBean;
import com.cn.speedchat.greendao.CommentsBean;
import com.cn.speedchat.greendao.ReleaseUser;
import com.cn.speedchat.greendao.DuanZiBean;

import com.cn.speedchat.greendao.GifitemBeanDao;
import com.cn.speedchat.greendao.PictureBeanDao;
import com.cn.speedchat.greendao.CommentsBeanDao;
import com.cn.speedchat.greendao.ReleaseUserDao;
import com.cn.speedchat.greendao.DuanZiBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gifitemBeanDaoConfig;
    private final DaoConfig pictureBeanDaoConfig;
    private final DaoConfig commentsBeanDaoConfig;
    private final DaoConfig releaseUserDaoConfig;
    private final DaoConfig duanZiBeanDaoConfig;

    private final GifitemBeanDao gifitemBeanDao;
    private final PictureBeanDao pictureBeanDao;
    private final CommentsBeanDao commentsBeanDao;
    private final ReleaseUserDao releaseUserDao;
    private final DuanZiBeanDao duanZiBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gifitemBeanDaoConfig = daoConfigMap.get(GifitemBeanDao.class).clone();
        gifitemBeanDaoConfig.initIdentityScope(type);

        pictureBeanDaoConfig = daoConfigMap.get(PictureBeanDao.class).clone();
        pictureBeanDaoConfig.initIdentityScope(type);

        commentsBeanDaoConfig = daoConfigMap.get(CommentsBeanDao.class).clone();
        commentsBeanDaoConfig.initIdentityScope(type);

        releaseUserDaoConfig = daoConfigMap.get(ReleaseUserDao.class).clone();
        releaseUserDaoConfig.initIdentityScope(type);

        duanZiBeanDaoConfig = daoConfigMap.get(DuanZiBeanDao.class).clone();
        duanZiBeanDaoConfig.initIdentityScope(type);

        gifitemBeanDao = new GifitemBeanDao(gifitemBeanDaoConfig, this);
        pictureBeanDao = new PictureBeanDao(pictureBeanDaoConfig, this);
        commentsBeanDao = new CommentsBeanDao(commentsBeanDaoConfig, this);
        releaseUserDao = new ReleaseUserDao(releaseUserDaoConfig, this);
        duanZiBeanDao = new DuanZiBeanDao(duanZiBeanDaoConfig, this);

        registerDao(GifitemBean.class, gifitemBeanDao);
        registerDao(PictureBean.class, pictureBeanDao);
        registerDao(CommentsBean.class, commentsBeanDao);
        registerDao(ReleaseUser.class, releaseUserDao);
        registerDao(DuanZiBean.class, duanZiBeanDao);
    }
    
    public void clear() {
        gifitemBeanDaoConfig.getIdentityScope().clear();
        pictureBeanDaoConfig.getIdentityScope().clear();
        commentsBeanDaoConfig.getIdentityScope().clear();
        releaseUserDaoConfig.getIdentityScope().clear();
        duanZiBeanDaoConfig.getIdentityScope().clear();
    }

    public GifitemBeanDao getGifitemBeanDao() {
        return gifitemBeanDao;
    }

    public PictureBeanDao getPictureBeanDao() {
        return pictureBeanDao;
    }

    public CommentsBeanDao getCommentsBeanDao() {
        return commentsBeanDao;
    }

    public ReleaseUserDao getReleaseUserDao() {
        return releaseUserDao;
    }

    public DuanZiBeanDao getDuanZiBeanDao() {
        return duanZiBeanDao;
    }

}
