package com.cn.speedchat.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RELEASEUSER.
 */
public class ReleaseUser {

    private Long id;
    private long NETid;
    /** Not-null value. */
    private String username;
    /** Not-null value. */
    private String userProfile;

    public ReleaseUser() {
    }

    public ReleaseUser(Long id) {
        this.id = id;
    }

    public ReleaseUser(Long id, long NETid, String username, String userProfile) {
        this.id = id;
        this.NETid = NETid;
        this.username = username;
        this.userProfile = userProfile;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getNETid() {
        return NETid;
    }

    public void setNETid(long NETid) {
        this.NETid = NETid;
    }

    /** Not-null value. */
    public String getUsername() {
        return username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(String username) {
        this.username = username;
    }

    /** Not-null value. */
    public String getUserProfile() {
        return userProfile;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserProfile(String userProfile) {
        this.userProfile = userProfile;
    }

}
